ARCHS = armv7 armv7s arm64

include /var/theos/makefiles/common.mk

TWEAK_NAME = TimerCL
TimerCL_FILES = Tweak.xm
TimerCL_FRAMEWORKS = Foundation CoreFoundation CoreTelephony
ADDITIONAL_OBJCFLAGS = -fobjc-arc

include /var/theos/makefiles/tweak.mk
